// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      throw UnsupportedError(
        'DefaultFirebaseOptions have not been configured for web - '
        'you can reconfigure this by running the FlutterFire CLI again.',
      );
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBjk3pHi9hAmJYtebCXqmqKUETCCezkpIw',
    appId: '1:438622614307:android:22141680f92f8e57d7d296',
    messagingSenderId: '438622614307',
    projectId: 'uat-project-af607',
    storageBucket: 'uat-project-af607.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAc4bwUD5KIoUxGELDNMh5AZWNyLNsx2fY',
    appId: '1:438622614307:ios:fb5b0d74ac4b8e07d7d296',
    messagingSenderId: '438622614307',
    projectId: 'uat-project-af607',
    storageBucket: 'uat-project-af607.firebasestorage.app',
    iosBundleId: 'com.example.uatProject',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAc4bwUD5KIoUxGELDNMh5AZWNyLNsx2fY',
    appId: '1:438622614307:ios:fb5b0d74ac4b8e07d7d296',
    messagingSenderId: '438622614307',
    projectId: 'uat-project-af607',
    storageBucket: 'uat-project-af607.firebasestorage.app',
    iosBundleId: 'com.example.uatProject',
  );

}